name: Lint

on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: golangci/golangci-lint-action@v3
        with:
          args: --disable=errcheck --timeout=5m
